### ISSUE TITLE
网站链接失效？

### ISSUE THREAD

**Issue by WeileiZeng** [wuhan2020/rest-api#10]
## 当前问题
https://vsw505fxbitp.leanapp.cn/ 无效

**Comment by zhaofeng-shu33** [comment]
Thanks for your issue. But I am afraid this repo is not maintained any more

**Comment by TechQuery** [comment]
访问量下降后换成**￥1/天**的**入门级生产实例**后几天扣费到欠费，切换到免费版实例就好了，感谢您的反馈！

我做的东西都一直维护着 @zhaofeng-shu33
