### ISSUE TITLE
捐款接收方存取

### ISSUE THREAD

**Issue by TechQuery** [wuhan2020/rest-api#7]
wuhan2020/WebApp#9

**Comment by TechQuery** [comment]
- 数据模型：https://github.com/wuhan2020/rest-api/blob/master/source/model/DonationRecipient.ts
- 接口逻辑：https://github.com/wuhan2020/rest-api/blob/master/source/controller/DonationRecipient.ts

**Comment by holidaying** [comment]
数据模型404

**Comment by holidaying** [comment]
> * 数据模型：https://github.com/wuhan2020/rest-api/blob/master/source/model/DonationRecipient.ts
> * 接口逻辑：https://github.com/wuhan2020/rest-api/blob/master/source/controller/DonationRecipient.ts
数据模型页面404

**Comment by holidaying** [comment]
数据模型404

**Comment by TechQuery** [comment]
@holidaying 请执行 `lean switch` 切换到 `WuHan-2020-test` 应用
https://github.com/wuhan2020/rest-api#%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91
