### ISSUE TITLE
api调试

### ISSUE THREAD

**Issue by boykait** [wuhan2020/rest-api#8]
调试可以用postman类似的工具吗，接口报403，如何获取用户认证信息，

**Comment by boykait** [comment]
不是403，是这种：
{"name":"AuthorizationRequiredError","message":"Authorization is required for request on GET /user","stack":"Error: \n    at AuthorizationRequiredError.HttpError [as constructor] (F:\\wuhan\\src\\http-error\\HttpError.ts:19:22)\n    at AuthorizationRequiredError.UnauthorizedError [as constructor] (F:\\wuhan\\src\\http-error\\UnauthorizedError.ts:10:9)\n    at new AuthorizationRequiredError (F:\\wuhan\\src\\error\\AuthorizationRequiredError.ts:12:9)\n    at handleError_1 (F:\\wuhan\\src\\driver\\koa\\KoaDriver.ts:87:87)\n    at F:\\wuhan\\src\\driver\\koa\\KoaDriver.ts:99:32\n    at dispatch (F:\\wuhan\\rest-api\\node_modules\\koa-compose\\index.js:42:32)\n    at F:\\wuhan\\rest-api\\node_modules\\koa-router\\lib\\router.js:353:16\n    at dispatch (F:\\wuhan\\rest-api\\node_modules\\koa-compose\\index.js:42:32)\n    at F:\\wuhan\\rest-api\\node_modules\\koa-compose\\index.js:34:12\n    at dispatch (F:\\wuhan\\rest-api\\node_modules\\koa-router\\lib\\router.js:358:31)"}

**Comment by TechQuery** [comment]
需要先登录 —— POST `/session`（[测试账号](https://github.com/wuhan2020/rest-api#%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE)）
